### ISSUE TITLE
找不到 fabric2,0类型的账户

### ISSUE THREAD

**Issue by ningtianyang** [WeBankBlockchain/WeCross-Fabric2-Stub#6]
1.按照教程部署后 deploy会失败，我就手动在通道里面部署了proxy合约
2.现在router能够启动，但是调用会失败提示：Account with type 'Fabric2.0' not found for org1-admin
3.我有执行过 bash add_account.sh -t Fabric2.0 -n fabric_admin 命令
4.定时任务也一直在刷：
WARN InterchainJob() - Failed to get interchain requests, path: payment.fabric.WeCrossHub, errorMessage: Account with type 'Fabric2.0' not found for org1-admin

**Comment by JimmyShi22** [comment]
开发中，目前为dev版本，暂未发布。
基础框架有了，目前还差几个点未完成，开发中，感兴趣可以一起开发，快速用上。 👍 
微信号：jimmy_shixiang22

**Comment by ningtianyang** [comment]
已解决。
解决方式为：
 1.router 启动后 ,配置一个对应的Console。
 2.进入console 将 router里面的account拷贝过来
cp -r ${ROOT}/bcos/accounts/* ${ROOT}/WeCross-Console/conf/accounts/
 3.  登录 addChainAccount
  addChainAccount GM_BCOS2.0 conf/accounts/${name}/${address}.public.pem conf/accounts/${name}/${address}.pem ${address} true
 5. 在数据库里面改成2.0 就能通过sdk调用了
 表（t_chain_accounts）

**Comment by morebtcg** [comment]
addChainAccount命令需要增加对2.0的支持

**Comment by JimmyShi22** [comment]
已发布，欢迎尝试
