### ISSUE TITLE
代理合约及桥接合约 部分引入包的位置已经替换

### ISSUE THREAD

**Issue by ningtianyang** [WeBankBlockchain/WeCross-Fabric2-Stub#7]
原来的引入地址为:
	"github.com/hyperledger/fabric/core/chaincode/shim"
        "github.com/hyperledger/fabric/protos/peer"
现在的引入位置为：
	"github.com/hyperledger/fabric-chaincode-go/shim"
	"github.com/hyperledger/fabric-protos-go/peer"

**Comment by JimmyShi22** [comment]
已发布，欢迎尝试
